
<section class="section ban-chay-nhat-tuan" id="section_661749377">
<div class="bg section-bg fill bg-fill  bg-loaded"></div>
    <div class="section-content relative">
<?php $new = $data['detailnew']; ?>
<div class="product-info summary entry-summary col col-fit product-summary">
    <div class="price-wrapper"><p class="price product-page-price price-not-in-stock"> <span class="woocommerce-Price-amount amount"><?= $new['title'] ?></strong><span class="woocommerce-Price-currencySymbol"></span></span></p></div>
    <div class="product-short-description"><p><?= $new['content'] ?></p></div>
    <div class="product_meta"> <span class="sku_wrapper"></span></div>
    <div class="thong-tin-shop">
    </div>
    <div class="social-icons share-icons share-row relative"><a href="whatsapp://send?text=Balo%20laptop%20nam%20n%E1%BB%AF%20c%E1%BB%A1%20l%E1%BB%9Bn%20SID59040 - http://shop2.ninhbinhweb.net/san-pham/balo-laptop-nam-nu-co-lon-sid59040/" data-action="share/whatsapp/share" class="icon button circle is-outline tooltip whatsapp show-for-medium" title="Share on WhatsApp"><i class="icon-phone"></i></a><a href="//www.facebook.com/sharer.php?u=http://shop2.ninhbinhweb.net/san-pham/balo-laptop-nam-nu-co-lon-sid59040/" data-label="Facebook" onclick="window.open(this.href,this.title,'width=500,height=500,top=300px,left=300px');  return false;" rel="noopener noreferrer nofollow" target="_blank" class="icon button circle is-outline tooltip facebook" title="Share on Facebook"><i class="icon-facebook"></i></a><a href="//twitter.com/share?url=http://shop2.ninhbinhweb.net/san-pham/balo-laptop-nam-nu-co-lon-sid59040/" onclick="window.open(this.href,this.title,'width=500,height=500,top=300px,left=300px');  return false;" rel="noopener noreferrer nofollow" target="_blank" class="icon button circle is-outline tooltip twitter" title="Share on Twitter"><i class="icon-twitter"></i></a><a href="mailto:enteryour@addresshere.com?subject=Balo%20laptop%20nam%20n%E1%BB%AF%20c%E1%BB%A1%20l%E1%BB%9Bn%20SID59040&body=Check%20this%20out:%20http://shop2.ninhbinhweb.net/san-pham/balo-laptop-nam-nu-co-lon-sid59040/" rel="nofollow" class="icon button circle is-outline tooltip email" title="Email to a Friend"><i class="icon-envelop"></i></a><a href="//pinterest.com/pin/create/button/?url=http://shop2.ninhbinhweb.net/san-pham/balo-laptop-nam-nu-co-lon-sid59040/&media=http://shop2.ninhbinhweb.net/wp-content/uploads/2018/07/a1.jpg&description=Balo%20laptop%20nam%20n%E1%BB%AF%20c%E1%BB%A1%20l%E1%BB%9Bn%20SID59040" onclick="window.open(this.href,this.title,'width=500,height=500,top=300px,left=300px');  return false;" rel="noopener noreferrer nofollow" target="_blank" class="icon button circle is-outline tooltip pinterest" title="Pin on Pinterest"><i class="icon-pinterest"></i></a><a href="//plus.google.com/share?url=http://shop2.ninhbinhweb.net/san-pham/balo-laptop-nam-nu-co-lon-sid59040/" target="_blank" class="icon button circle is-outline tooltip google-plus" onclick="window.open(this.href,this.title,'width=500,height=500,top=300px,left=300px');  return false;" rel="noopener noreferrer nofollow" title="Share on Google+"><i class="icon-google-plus"></i></a><a href="//www.linkedin.com/shareArticle?mini=true&url=http://shop2.ninhbinhweb.net/san-pham/balo-laptop-nam-nu-co-lon-sid59040/&title=Balo%20laptop%20nam%20n%E1%BB%AF%20c%E1%BB%A1%20l%E1%BB%9Bn%20SID59040" onclick="window.open(this.href,this.title,'width=500,height=500,top=300px,left=300px');  return false;" rel="noopener noreferrer nofollow" target="_blank" class="icon button circle is-outline tooltip linkedin" title="Share on LinkedIn"><i class="icon-linkedin"></i></a></div>
</div>
</div>
</div>
</section>
   